-- NFL Predictions Database Schema
-- Auto-generated from Parquet files by generate_schema.py
-- Re-run to regenerate: python src/nfl/db/generate_schema.py

-- players: 39 columns from data/nfl/players/players.parquet
CREATE TABLE IF NOT EXISTS players (
    id SERIAL PRIMARY KEY,
    "gsis_id" TEXT,
    "display_name" TEXT,
    "common_first_name" TEXT,
    "first_name" TEXT,
    "last_name" TEXT,
    "short_name" TEXT,
    "football_name" TEXT,
    "suffix" TEXT,
    "esb_id" TEXT,
    "nfl_id" TEXT,
    "pfr_id" TEXT,
    "pff_id" TEXT,
    "otc_id" TEXT,
    "espn_id" TEXT,
    "smart_id" TEXT,
    "birth_date" TEXT,
    "position_group" TEXT,
    "position" TEXT,
    "ngs_position_group" TEXT,
    "ngs_position" TEXT,
    "height" DOUBLE PRECISION,
    "weight" DOUBLE PRECISION,
    "headshot" TEXT,
    "college_name" TEXT,
    "college_conference" TEXT,
    "jersey_number" TEXT,
    "rookie_season" INTEGER,
    "last_season" INTEGER,
    "latest_team" TEXT,
    "status" TEXT,
    "ngs_status" TEXT,
    "ngs_status_short_description" TEXT,
    "years_of_experience" INTEGER,
    "pff_position" TEXT,
    "pff_status" TEXT,
    "draft_year" DOUBLE PRECISION,
    "draft_round" DOUBLE PRECISION,
    "draft_pick" DOUBLE PRECISION,
    "draft_team" TEXT,
    UNIQUE ("gsis_id")
);

-- games: 48 columns from data/nfl/schedules/schedules_2024.parquet
CREATE TABLE IF NOT EXISTS games (
    id SERIAL PRIMARY KEY,
    "game_id" TEXT,
    "season" INTEGER,
    "game_type" TEXT,
    "week" INTEGER,
    "gameday" TEXT,
    "weekday" TEXT,
    "gametime" TEXT,
    "away_team" TEXT,
    "away_score" INTEGER,
    "home_team" TEXT,
    "home_score" INTEGER,
    "location" TEXT,
    "result" INTEGER,
    "total" INTEGER,
    "overtime" INTEGER,
    "old_game_id" TEXT,
    "gsis" INTEGER,
    "nfl_detail_id" TEXT,
    "pfr" TEXT,
    "pff" DOUBLE PRECISION,
    "espn" TEXT,
    "ftn" DOUBLE PRECISION,
    "away_rest" INTEGER,
    "home_rest" INTEGER,
    "away_moneyline" INTEGER,
    "home_moneyline" INTEGER,
    "spread_line" DOUBLE PRECISION,
    "away_spread_odds" INTEGER,
    "home_spread_odds" INTEGER,
    "total_line" DOUBLE PRECISION,
    "under_odds" INTEGER,
    "over_odds" INTEGER,
    "div_game" INTEGER,
    "roof" TEXT,
    "surface" TEXT,
    "temp" DOUBLE PRECISION,
    "wind" DOUBLE PRECISION,
    "away_qb_id" TEXT,
    "home_qb_id" TEXT,
    "away_qb_name" TEXT,
    "home_qb_name" TEXT,
    "away_coach" TEXT,
    "home_coach" TEXT,
    "referee" TEXT,
    "stadium_id" TEXT,
    "stadium" TEXT,
    "home_implied_total" DOUBLE PRECISION,
    "away_implied_total" DOUBLE PRECISION,
    UNIQUE ("game_id")
);

-- weekly_stats: 114 columns from data/nfl/player_stats/player_stats_2024.parquet
CREATE TABLE IF NOT EXISTS weekly_stats (
    id SERIAL PRIMARY KEY,
    "player_id" TEXT,
    "player_name" TEXT,
    "player_display_name" TEXT,
    "position" TEXT,
    "position_group" TEXT,
    "headshot_url" TEXT,
    "season" INTEGER,
    "week" INTEGER,
    "season_type" TEXT,
    "team" TEXT,
    "opponent_team" TEXT,
    "completions" INTEGER,
    "attempts" INTEGER,
    "passing_yards" INTEGER,
    "passing_tds" INTEGER,
    "passing_interceptions" INTEGER,
    "sacks_suffered" INTEGER,
    "sack_yards_lost" INTEGER,
    "sack_fumbles" INTEGER,
    "sack_fumbles_lost" INTEGER,
    "passing_air_yards" INTEGER,
    "passing_yards_after_catch" INTEGER,
    "passing_first_downs" INTEGER,
    "passing_epa" DOUBLE PRECISION,
    "passing_cpoe" DOUBLE PRECISION,
    "passing_2pt_conversions" INTEGER,
    "pacr" DOUBLE PRECISION,
    "carries" INTEGER,
    "rushing_yards" INTEGER,
    "rushing_tds" INTEGER,
    "rushing_fumbles" INTEGER,
    "rushing_fumbles_lost" INTEGER,
    "rushing_first_downs" INTEGER,
    "rushing_epa" DOUBLE PRECISION,
    "rushing_2pt_conversions" INTEGER,
    "receptions" INTEGER,
    "targets" INTEGER,
    "receiving_yards" INTEGER,
    "receiving_tds" INTEGER,
    "receiving_fumbles" INTEGER,
    "receiving_fumbles_lost" INTEGER,
    "receiving_air_yards" INTEGER,
    "receiving_yards_after_catch" INTEGER,
    "receiving_first_downs" INTEGER,
    "receiving_epa" DOUBLE PRECISION,
    "receiving_2pt_conversions" INTEGER,
    "racr" DOUBLE PRECISION,
    "target_share" DOUBLE PRECISION,
    "air_yards_share" DOUBLE PRECISION,
    "wopr" DOUBLE PRECISION,
    "special_teams_tds" INTEGER,
    "def_tackles_solo" INTEGER,
    "def_tackles_with_assist" INTEGER,
    "def_tackle_assists" INTEGER,
    "def_tackles_for_loss" INTEGER,
    "def_tackles_for_loss_yards" INTEGER,
    "def_fumbles_forced" INTEGER,
    "def_sacks" DOUBLE PRECISION,
    "def_sack_yards" DOUBLE PRECISION,
    "def_qb_hits" INTEGER,
    "def_interceptions" INTEGER,
    "def_interception_yards" INTEGER,
    "def_pass_defended" INTEGER,
    "def_tds" INTEGER,
    "def_fumbles" INTEGER,
    "def_safeties" INTEGER,
    "misc_yards" INTEGER,
    "fumble_recovery_own" INTEGER,
    "fumble_recovery_yards_own" INTEGER,
    "fumble_recovery_opp" INTEGER,
    "fumble_recovery_yards_opp" INTEGER,
    "fumble_recovery_tds" INTEGER,
    "penalties" INTEGER,
    "penalty_yards" INTEGER,
    "punt_returns" INTEGER,
    "punt_return_yards" INTEGER,
    "kickoff_returns" INTEGER,
    "kickoff_return_yards" INTEGER,
    "fg_made" INTEGER,
    "fg_att" INTEGER,
    "fg_missed" INTEGER,
    "fg_blocked" INTEGER,
    "fg_long" DOUBLE PRECISION,
    "fg_pct" DOUBLE PRECISION,
    "fg_made_0_19" INTEGER,
    "fg_made_20_29" INTEGER,
    "fg_made_30_39" INTEGER,
    "fg_made_40_49" INTEGER,
    "fg_made_50_59" INTEGER,
    "fg_made_60_" INTEGER,
    "fg_missed_0_19" INTEGER,
    "fg_missed_20_29" INTEGER,
    "fg_missed_30_39" INTEGER,
    "fg_missed_40_49" INTEGER,
    "fg_missed_50_59" INTEGER,
    "fg_missed_60_" INTEGER,
    "fg_made_list" TEXT,
    "fg_missed_list" TEXT,
    "fg_blocked_list" TEXT,
    "fg_made_distance" INTEGER,
    "fg_missed_distance" INTEGER,
    "fg_blocked_distance" INTEGER,
    "pat_made" INTEGER,
    "pat_att" INTEGER,
    "pat_missed" INTEGER,
    "pat_blocked" INTEGER,
    "pat_pct" DOUBLE PRECISION,
    "gwfg_made" INTEGER,
    "gwfg_att" INTEGER,
    "gwfg_missed" INTEGER,
    "gwfg_blocked" INTEGER,
    "gwfg_distance" INTEGER,
    "fantasy_points" DOUBLE PRECISION,
    "fantasy_points_ppr" DOUBLE PRECISION,
    UNIQUE ("player_id", "season", "week")
);

-- injuries: 16 columns from data/nfl/injuries/injuries_2024.parquet
CREATE TABLE IF NOT EXISTS injuries (
    id SERIAL PRIMARY KEY,
    "season" INTEGER,
    "game_type" TEXT,
    "team" TEXT,
    "week" INTEGER,
    "gsis_id" TEXT,
    "position" TEXT,
    "full_name" TEXT,
    "first_name" TEXT,
    "last_name" TEXT,
    "report_primary_injury" TEXT,
    "report_secondary_injury" TEXT,
    "report_status" TEXT,
    "practice_primary_injury" TEXT,
    "practice_secondary_injury" TEXT,
    "practice_status" TEXT,
    "date_modified" TIMESTAMPTZ
);

-- depth_charts: 15 columns from data/nfl/depth_charts/depth_charts_2024.parquet
CREATE TABLE IF NOT EXISTS depth_charts (
    id SERIAL PRIMARY KEY,
    "season" INTEGER,
    "club_code" TEXT,
    "week" DOUBLE PRECISION,
    "game_type" TEXT,
    "depth_team" TEXT,
    "last_name" TEXT,
    "first_name" TEXT,
    "football_name" TEXT,
    "formation" TEXT,
    "gsis_id" TEXT,
    "jersey_number" TEXT,
    "position" TEXT,
    "elias_id" TEXT,
    "depth_position" TEXT,
    "full_name" TEXT
);

-- snap_counts: 16 columns from data/nfl/snap_counts/snap_counts_2024.parquet
CREATE TABLE IF NOT EXISTS snap_counts (
    id SERIAL PRIMARY KEY,
    "game_id" TEXT,
    "pfr_game_id" TEXT,
    "season" INTEGER,
    "game_type" TEXT,
    "week" INTEGER,
    "player" TEXT,
    "pfr_player_id" TEXT,
    "position" TEXT,
    "team" TEXT,
    "opponent" TEXT,
    "offense_snaps" DOUBLE PRECISION,
    "offense_pct" DOUBLE PRECISION,
    "defense_snaps" DOUBLE PRECISION,
    "defense_pct" DOUBLE PRECISION,
    "st_snaps" DOUBLE PRECISION,
    "st_pct" DOUBLE PRECISION
);

-- pfr_pass_advstats: 24 columns from data/nfl/pfr_advstats/pfr_pass_2024.parquet
CREATE TABLE IF NOT EXISTS pfr_pass_advstats (
    id SERIAL PRIMARY KEY,
    "game_id" TEXT,
    "pfr_game_id" TEXT,
    "season" INTEGER,
    "week" INTEGER,
    "game_type" TEXT,
    "team" TEXT,
    "opponent" TEXT,
    "pfr_player_name" TEXT,
    "pfr_player_id" TEXT,
    "passing_drops" DOUBLE PRECISION,
    "passing_drop_pct" DOUBLE PRECISION,
    "receiving_drop" DOUBLE PRECISION,
    "receiving_drop_pct" DOUBLE PRECISION,
    "passing_bad_throws" DOUBLE PRECISION,
    "passing_bad_throw_pct" DOUBLE PRECISION,
    "times_sacked" DOUBLE PRECISION,
    "times_blitzed" DOUBLE PRECISION,
    "times_hurried" DOUBLE PRECISION,
    "times_hit" DOUBLE PRECISION,
    "times_pressured" DOUBLE PRECISION,
    "times_pressured_pct" DOUBLE PRECISION,
    "def_times_blitzed" DOUBLE PRECISION,
    "def_times_hurried" DOUBLE PRECISION,
    "def_times_hitqb" DOUBLE PRECISION
);

-- pfr_rush_advstats: 16 columns from data/nfl/pfr_advstats/pfr_rush_2024.parquet
CREATE TABLE IF NOT EXISTS pfr_rush_advstats (
    id SERIAL PRIMARY KEY,
    "game_id" TEXT,
    "pfr_game_id" TEXT,
    "season" INTEGER,
    "week" INTEGER,
    "game_type" TEXT,
    "team" TEXT,
    "opponent" TEXT,
    "pfr_player_name" TEXT,
    "pfr_player_id" TEXT,
    "carries" DOUBLE PRECISION,
    "rushing_yards_before_contact" DOUBLE PRECISION,
    "rushing_yards_before_contact_avg" DOUBLE PRECISION,
    "rushing_yards_after_contact" DOUBLE PRECISION,
    "rushing_yards_after_contact_avg" DOUBLE PRECISION,
    "rushing_broken_tackles" DOUBLE PRECISION,
    "receiving_broken_tackles" DOUBLE PRECISION
);

-- pfr_rec_advstats: 17 columns from data/nfl/pfr_advstats/pfr_rec_2024.parquet
CREATE TABLE IF NOT EXISTS pfr_rec_advstats (
    id SERIAL PRIMARY KEY,
    "game_id" TEXT,
    "pfr_game_id" TEXT,
    "season" INTEGER,
    "week" INTEGER,
    "game_type" TEXT,
    "team" TEXT,
    "opponent" TEXT,
    "pfr_player_name" TEXT,
    "pfr_player_id" TEXT,
    "rushing_broken_tackles" DOUBLE PRECISION,
    "receiving_broken_tackles" DOUBLE PRECISION,
    "passing_drops" DOUBLE PRECISION,
    "passing_drop_pct" DOUBLE PRECISION,
    "receiving_drop" DOUBLE PRECISION,
    "receiving_drop_pct" DOUBLE PRECISION,
    "receiving_int" DOUBLE PRECISION,
    "receiving_rat" DOUBLE PRECISION
);

-- ngs_passing: 29 columns from data/nfl/nextgen_stats/ngs_passing_2024.parquet
CREATE TABLE IF NOT EXISTS ngs_passing (
    id SERIAL PRIMARY KEY,
    "season" INTEGER,
    "season_type" TEXT,
    "week" INTEGER,
    "player_display_name" TEXT,
    "player_position" TEXT,
    "team_abbr" TEXT,
    "avg_time_to_throw" DOUBLE PRECISION,
    "avg_completed_air_yards" DOUBLE PRECISION,
    "avg_intended_air_yards" DOUBLE PRECISION,
    "avg_air_yards_differential" DOUBLE PRECISION,
    "aggressiveness" DOUBLE PRECISION,
    "max_completed_air_distance" DOUBLE PRECISION,
    "avg_air_yards_to_sticks" DOUBLE PRECISION,
    "attempts" INTEGER,
    "pass_yards" INTEGER,
    "pass_touchdowns" INTEGER,
    "interceptions" INTEGER,
    "passer_rating" DOUBLE PRECISION,
    "completions" INTEGER,
    "completion_percentage" DOUBLE PRECISION,
    "expected_completion_percentage" DOUBLE PRECISION,
    "completion_percentage_above_expectation" DOUBLE PRECISION,
    "avg_air_distance" DOUBLE PRECISION,
    "max_air_distance" DOUBLE PRECISION,
    "player_gsis_id" TEXT,
    "player_first_name" TEXT,
    "player_last_name" TEXT,
    "player_jersey_number" INTEGER,
    "player_short_name" TEXT
);

-- ngs_rushing: 22 columns from data/nfl/nextgen_stats/ngs_rushing_2024.parquet
CREATE TABLE IF NOT EXISTS ngs_rushing (
    id SERIAL PRIMARY KEY,
    "season" INTEGER,
    "season_type" TEXT,
    "week" INTEGER,
    "player_display_name" TEXT,
    "player_position" TEXT,
    "team_abbr" TEXT,
    "efficiency" DOUBLE PRECISION,
    "percent_attempts_gte_eight_defenders" DOUBLE PRECISION,
    "avg_time_to_los" DOUBLE PRECISION,
    "rush_attempts" INTEGER,
    "rush_yards" INTEGER,
    "avg_rush_yards" DOUBLE PRECISION,
    "rush_touchdowns" INTEGER,
    "player_gsis_id" TEXT,
    "player_first_name" TEXT,
    "player_last_name" TEXT,
    "player_jersey_number" INTEGER,
    "player_short_name" TEXT,
    "expected_rush_yards" DOUBLE PRECISION,
    "rush_yards_over_expected" DOUBLE PRECISION,
    "rush_yards_over_expected_per_att" DOUBLE PRECISION,
    "rush_pct_over_expected" DOUBLE PRECISION
);

-- ngs_receiving: 23 columns from data/nfl/nextgen_stats/ngs_receiving_2024.parquet
CREATE TABLE IF NOT EXISTS ngs_receiving (
    id SERIAL PRIMARY KEY,
    "season" INTEGER,
    "season_type" TEXT,
    "week" INTEGER,
    "player_display_name" TEXT,
    "player_position" TEXT,
    "team_abbr" TEXT,
    "avg_cushion" DOUBLE PRECISION,
    "avg_separation" DOUBLE PRECISION,
    "avg_intended_air_yards" DOUBLE PRECISION,
    "percent_share_of_intended_air_yards" DOUBLE PRECISION,
    "receptions" INTEGER,
    "targets" INTEGER,
    "catch_percentage" DOUBLE PRECISION,
    "yards" DOUBLE PRECISION,
    "rec_touchdowns" INTEGER,
    "avg_yac" DOUBLE PRECISION,
    "avg_expected_yac" DOUBLE PRECISION,
    "avg_yac_above_expectation" DOUBLE PRECISION,
    "player_gsis_id" TEXT,
    "player_first_name" TEXT,
    "player_last_name" TEXT,
    "player_jersey_number" INTEGER,
    "player_short_name" TEXT
);

-- ff_opportunity: 159 columns from data/nfl/ff_opportunity/ff_opportunity_2024.parquet
CREATE TABLE IF NOT EXISTS ff_opportunity (
    id SERIAL PRIMARY KEY,
    "season" TEXT,
    "posteam" TEXT,
    "week" DOUBLE PRECISION,
    "game_id" TEXT,
    "player_id" TEXT,
    "full_name" TEXT,
    "position" TEXT,
    "pass_attempt" DOUBLE PRECISION,
    "rec_attempt" DOUBLE PRECISION,
    "rush_attempt" DOUBLE PRECISION,
    "pass_air_yards" DOUBLE PRECISION,
    "rec_air_yards" DOUBLE PRECISION,
    "pass_completions" DOUBLE PRECISION,
    "receptions" DOUBLE PRECISION,
    "pass_completions_exp" DOUBLE PRECISION,
    "receptions_exp" DOUBLE PRECISION,
    "pass_yards_gained" DOUBLE PRECISION,
    "rec_yards_gained" DOUBLE PRECISION,
    "rush_yards_gained" DOUBLE PRECISION,
    "pass_yards_gained_exp" DOUBLE PRECISION,
    "rec_yards_gained_exp" DOUBLE PRECISION,
    "rush_yards_gained_exp" DOUBLE PRECISION,
    "pass_touchdown" DOUBLE PRECISION,
    "rec_touchdown" DOUBLE PRECISION,
    "rush_touchdown" DOUBLE PRECISION,
    "pass_touchdown_exp" DOUBLE PRECISION,
    "rec_touchdown_exp" DOUBLE PRECISION,
    "rush_touchdown_exp" DOUBLE PRECISION,
    "pass_two_point_conv" DOUBLE PRECISION,
    "rec_two_point_conv" DOUBLE PRECISION,
    "rush_two_point_conv" DOUBLE PRECISION,
    "pass_two_point_conv_exp" DOUBLE PRECISION,
    "rec_two_point_conv_exp" DOUBLE PRECISION,
    "rush_two_point_conv_exp" DOUBLE PRECISION,
    "pass_first_down" DOUBLE PRECISION,
    "rec_first_down" DOUBLE PRECISION,
    "rush_first_down" DOUBLE PRECISION,
    "pass_first_down_exp" DOUBLE PRECISION,
    "rec_first_down_exp" DOUBLE PRECISION,
    "rush_first_down_exp" DOUBLE PRECISION,
    "pass_interception" DOUBLE PRECISION,
    "rec_interception" DOUBLE PRECISION,
    "pass_interception_exp" DOUBLE PRECISION,
    "rec_interception_exp" DOUBLE PRECISION,
    "rec_fumble_lost" DOUBLE PRECISION,
    "rush_fumble_lost" DOUBLE PRECISION,
    "pass_fantasy_points_exp" DOUBLE PRECISION,
    "rec_fantasy_points_exp" DOUBLE PRECISION,
    "rush_fantasy_points_exp" DOUBLE PRECISION,
    "pass_fantasy_points" DOUBLE PRECISION,
    "rec_fantasy_points" DOUBLE PRECISION,
    "rush_fantasy_points" DOUBLE PRECISION,
    "total_yards_gained" DOUBLE PRECISION,
    "total_yards_gained_exp" DOUBLE PRECISION,
    "total_touchdown" DOUBLE PRECISION,
    "total_touchdown_exp" DOUBLE PRECISION,
    "total_first_down" DOUBLE PRECISION,
    "total_first_down_exp" DOUBLE PRECISION,
    "total_fantasy_points" DOUBLE PRECISION,
    "total_fantasy_points_exp" DOUBLE PRECISION,
    "pass_completions_diff" DOUBLE PRECISION,
    "receptions_diff" DOUBLE PRECISION,
    "pass_yards_gained_diff" DOUBLE PRECISION,
    "rec_yards_gained_diff" DOUBLE PRECISION,
    "rush_yards_gained_diff" DOUBLE PRECISION,
    "pass_touchdown_diff" DOUBLE PRECISION,
    "rec_touchdown_diff" DOUBLE PRECISION,
    "rush_touchdown_diff" DOUBLE PRECISION,
    "pass_two_point_conv_diff" DOUBLE PRECISION,
    "rec_two_point_conv_diff" DOUBLE PRECISION,
    "rush_two_point_conv_diff" DOUBLE PRECISION,
    "pass_first_down_diff" DOUBLE PRECISION,
    "rec_first_down_diff" DOUBLE PRECISION,
    "rush_first_down_diff" DOUBLE PRECISION,
    "pass_interception_diff" DOUBLE PRECISION,
    "rec_interception_diff" DOUBLE PRECISION,
    "pass_fantasy_points_diff" DOUBLE PRECISION,
    "rec_fantasy_points_diff" DOUBLE PRECISION,
    "rush_fantasy_points_diff" DOUBLE PRECISION,
    "total_yards_gained_diff" DOUBLE PRECISION,
    "total_touchdown_diff" DOUBLE PRECISION,
    "total_first_down_diff" DOUBLE PRECISION,
    "total_fantasy_points_diff" DOUBLE PRECISION,
    "pass_attempt_team" DOUBLE PRECISION,
    "rec_attempt_team" DOUBLE PRECISION,
    "rush_attempt_team" DOUBLE PRECISION,
    "pass_air_yards_team" DOUBLE PRECISION,
    "rec_air_yards_team" DOUBLE PRECISION,
    "pass_completions_team" DOUBLE PRECISION,
    "receptions_team" DOUBLE PRECISION,
    "pass_completions_exp_team" DOUBLE PRECISION,
    "receptions_exp_team" DOUBLE PRECISION,
    "pass_yards_gained_team" DOUBLE PRECISION,
    "rec_yards_gained_team" DOUBLE PRECISION,
    "rush_yards_gained_team" DOUBLE PRECISION,
    "pass_yards_gained_exp_team" DOUBLE PRECISION,
    "rec_yards_gained_exp_team" DOUBLE PRECISION,
    "rush_yards_gained_exp_team" DOUBLE PRECISION,
    "pass_touchdown_team" DOUBLE PRECISION,
    "rec_touchdown_team" DOUBLE PRECISION,
    "rush_touchdown_team" DOUBLE PRECISION,
    "pass_touchdown_exp_team" DOUBLE PRECISION,
    "rec_touchdown_exp_team" DOUBLE PRECISION,
    "rush_touchdown_exp_team" DOUBLE PRECISION,
    "pass_two_point_conv_team" DOUBLE PRECISION,
    "rec_two_point_conv_team" DOUBLE PRECISION,
    "rush_two_point_conv_team" DOUBLE PRECISION,
    "pass_two_point_conv_exp_team" DOUBLE PRECISION,
    "rec_two_point_conv_exp_team" DOUBLE PRECISION,
    "rush_two_point_conv_exp_team" DOUBLE PRECISION,
    "pass_first_down_team" DOUBLE PRECISION,
    "rec_first_down_team" DOUBLE PRECISION,
    "rush_first_down_team" DOUBLE PRECISION,
    "pass_first_down_exp_team" DOUBLE PRECISION,
    "rec_first_down_exp_team" DOUBLE PRECISION,
    "rush_first_down_exp_team" DOUBLE PRECISION,
    "pass_interception_team" DOUBLE PRECISION,
    "rec_interception_team" DOUBLE PRECISION,
    "pass_interception_exp_team" DOUBLE PRECISION,
    "rec_interception_exp_team" DOUBLE PRECISION,
    "rec_fumble_lost_team" DOUBLE PRECISION,
    "rush_fumble_lost_team" DOUBLE PRECISION,
    "pass_fantasy_points_exp_team" DOUBLE PRECISION,
    "rec_fantasy_points_exp_team" DOUBLE PRECISION,
    "rush_fantasy_points_exp_team" DOUBLE PRECISION,
    "pass_fantasy_points_team" DOUBLE PRECISION,
    "rec_fantasy_points_team" DOUBLE PRECISION,
    "rush_fantasy_points_team" DOUBLE PRECISION,
    "pass_completions_diff_team" DOUBLE PRECISION,
    "receptions_diff_team" DOUBLE PRECISION,
    "pass_yards_gained_diff_team" DOUBLE PRECISION,
    "rec_yards_gained_diff_team" DOUBLE PRECISION,
    "rush_yards_gained_diff_team" DOUBLE PRECISION,
    "pass_touchdown_diff_team" DOUBLE PRECISION,
    "rec_touchdown_diff_team" DOUBLE PRECISION,
    "rush_touchdown_diff_team" DOUBLE PRECISION,
    "pass_two_point_conv_diff_team" DOUBLE PRECISION,
    "rec_two_point_conv_diff_team" DOUBLE PRECISION,
    "rush_two_point_conv_diff_team" DOUBLE PRECISION,
    "pass_first_down_diff_team" DOUBLE PRECISION,
    "rec_first_down_diff_team" DOUBLE PRECISION,
    "rush_first_down_diff_team" DOUBLE PRECISION,
    "pass_interception_diff_team" DOUBLE PRECISION,
    "rec_interception_diff_team" DOUBLE PRECISION,
    "pass_fantasy_points_diff_team" DOUBLE PRECISION,
    "rec_fantasy_points_diff_team" DOUBLE PRECISION,
    "rush_fantasy_points_diff_team" DOUBLE PRECISION,
    "total_yards_gained_team" DOUBLE PRECISION,
    "total_yards_gained_exp_team" DOUBLE PRECISION,
    "total_yards_gained_diff_team" DOUBLE PRECISION,
    "total_touchdown_team" DOUBLE PRECISION,
    "total_touchdown_exp_team" DOUBLE PRECISION,
    "total_touchdown_diff_team" DOUBLE PRECISION,
    "total_first_down_team" DOUBLE PRECISION,
    "total_first_down_exp_team" DOUBLE PRECISION,
    "total_first_down_diff_team" DOUBLE PRECISION,
    "total_fantasy_points_team" DOUBLE PRECISION,
    "total_fantasy_points_exp_team" DOUBLE PRECISION,
    "total_fantasy_points_diff_team" DOUBLE PRECISION
);

-- team_stats: 102 columns from data/nfl/team_stats/team_stats_2024.parquet
CREATE TABLE IF NOT EXISTS team_stats (
    id SERIAL PRIMARY KEY,
    "season" INTEGER,
    "week" INTEGER,
    "team" TEXT,
    "season_type" TEXT,
    "opponent_team" TEXT,
    "completions" INTEGER,
    "attempts" INTEGER,
    "passing_yards" INTEGER,
    "passing_tds" INTEGER,
    "passing_interceptions" INTEGER,
    "sacks_suffered" INTEGER,
    "sack_yards_lost" INTEGER,
    "sack_fumbles" INTEGER,
    "sack_fumbles_lost" INTEGER,
    "passing_air_yards" INTEGER,
    "passing_yards_after_catch" INTEGER,
    "passing_first_downs" INTEGER,
    "passing_epa" DOUBLE PRECISION,
    "passing_cpoe" DOUBLE PRECISION,
    "passing_2pt_conversions" INTEGER,
    "carries" INTEGER,
    "rushing_yards" INTEGER,
    "rushing_tds" INTEGER,
    "rushing_fumbles" INTEGER,
    "rushing_fumbles_lost" INTEGER,
    "rushing_first_downs" INTEGER,
    "rushing_epa" DOUBLE PRECISION,
    "rushing_2pt_conversions" INTEGER,
    "receptions" INTEGER,
    "targets" INTEGER,
    "receiving_yards" INTEGER,
    "receiving_tds" INTEGER,
    "receiving_fumbles" INTEGER,
    "receiving_fumbles_lost" INTEGER,
    "receiving_air_yards" INTEGER,
    "receiving_yards_after_catch" INTEGER,
    "receiving_first_downs" INTEGER,
    "receiving_epa" DOUBLE PRECISION,
    "receiving_2pt_conversions" INTEGER,
    "special_teams_tds" INTEGER,
    "def_tackles_solo" INTEGER,
    "def_tackles_with_assist" INTEGER,
    "def_tackle_assists" INTEGER,
    "def_tackles_for_loss" INTEGER,
    "def_tackles_for_loss_yards" INTEGER,
    "def_fumbles_forced" INTEGER,
    "def_sacks" DOUBLE PRECISION,
    "def_sack_yards" DOUBLE PRECISION,
    "def_qb_hits" INTEGER,
    "def_interceptions" INTEGER,
    "def_interception_yards" INTEGER,
    "def_pass_defended" INTEGER,
    "def_tds" INTEGER,
    "def_fumbles" INTEGER,
    "def_safeties" INTEGER,
    "misc_yards" INTEGER,
    "fumble_recovery_own" INTEGER,
    "fumble_recovery_yards_own" INTEGER,
    "fumble_recovery_opp" INTEGER,
    "fumble_recovery_yards_opp" INTEGER,
    "fumble_recovery_tds" INTEGER,
    "penalties" INTEGER,
    "penalty_yards" INTEGER,
    "timeouts" INTEGER,
    "punt_returns" INTEGER,
    "punt_return_yards" INTEGER,
    "kickoff_returns" INTEGER,
    "kickoff_return_yards" INTEGER,
    "fg_made" INTEGER,
    "fg_att" INTEGER,
    "fg_missed" INTEGER,
    "fg_blocked" INTEGER,
    "fg_long" DOUBLE PRECISION,
    "fg_pct" DOUBLE PRECISION,
    "fg_made_0_19" INTEGER,
    "fg_made_20_29" INTEGER,
    "fg_made_30_39" INTEGER,
    "fg_made_40_49" INTEGER,
    "fg_made_50_59" INTEGER,
    "fg_made_60_" INTEGER,
    "fg_missed_0_19" INTEGER,
    "fg_missed_20_29" INTEGER,
    "fg_missed_30_39" INTEGER,
    "fg_missed_40_49" INTEGER,
    "fg_missed_50_59" INTEGER,
    "fg_missed_60_" INTEGER,
    "fg_made_list" TEXT,
    "fg_missed_list" TEXT,
    "fg_blocked_list" TEXT,
    "fg_made_distance" INTEGER,
    "fg_missed_distance" INTEGER,
    "fg_blocked_distance" INTEGER,
    "pat_made" INTEGER,
    "pat_att" INTEGER,
    "pat_missed" INTEGER,
    "pat_blocked" INTEGER,
    "pat_pct" DOUBLE PRECISION,
    "gwfg_made" INTEGER,
    "gwfg_att" INTEGER,
    "gwfg_missed" INTEGER,
    "gwfg_blocked" INTEGER,
    "gwfg_distance" INTEGER,
    UNIQUE ("team", "season", "week")
);


-- Indexes for common query patterns
CREATE INDEX IF NOT EXISTS idx_weekly_stats_player ON weekly_stats ("player_id", "season", "week");
CREATE INDEX IF NOT EXISTS idx_weekly_stats_team ON weekly_stats ("team", "season", "week");
CREATE INDEX IF NOT EXISTS idx_injuries_player ON injuries ("gsis_id", "season", "week");
CREATE INDEX IF NOT EXISTS idx_snap_counts_player ON snap_counts ("pfr_player_id", "season", "week");
CREATE INDEX IF NOT EXISTS idx_depth_charts_player ON depth_charts ("gsis_id", "season", "week");
CREATE INDEX IF NOT EXISTS idx_ngs_passing_player ON ngs_passing ("player_gsis_id", "season", "week");
CREATE INDEX IF NOT EXISTS idx_ngs_rushing_player ON ngs_rushing ("player_gsis_id", "season", "week");
CREATE INDEX IF NOT EXISTS idx_ngs_receiving_player ON ngs_receiving ("player_gsis_id", "season", "week");
CREATE INDEX IF NOT EXISTS idx_ff_opp_player ON ff_opportunity ("player_id", "season", "week");
CREATE INDEX IF NOT EXISTS idx_pfr_pass_player ON pfr_pass_advstats ("pfr_player_id", "season", "week");
CREATE INDEX IF NOT EXISTS idx_pfr_rush_player ON pfr_rush_advstats ("pfr_player_id", "season", "week");
CREATE INDEX IF NOT EXISTS idx_pfr_rec_player ON pfr_rec_advstats ("pfr_player_id", "season", "week");
CREATE INDEX IF NOT EXISTS idx_team_stats_team ON team_stats ("team", "season", "week");
CREATE INDEX IF NOT EXISTS idx_games_season_week ON games ("season", "week");
CREATE INDEX IF NOT EXISTS idx_players_pfr ON players ("pfr_id");
CREATE INDEX IF NOT EXISTS idx_players_gsis ON players ("gsis_id");
