"""
File: src/nfl/column_mappings.py

Column display name mappings for NFL data
Maps raw API column names to human-readable display names
"""

COLUMN_DISPLAY_NAMES = {
    'player_id': 'Player ID',
    'player_name': 'Player Name',
    'player_display_name': 'Display Name',
    'position': 'Pos',
    'position_group': 'Pos Group',
    'headshot_url': 'Headshot',
    'season': 'Season',
    'week': 'Week',
    'season_type': 'Season Type',
    'team': 'Team',
    'opponent_team': 'Opp',
    'completions': 'Comp',
    'attempts': 'Att',
    'passing_yards': 'Pass Yds',
    'passing_tds': 'Pass TDs',
    'passing_interceptions': 'Pass INTs',
    'sacks_suffered': 'Sacks Taken',
    'sack_yards_lost': 'Sack Yds Lost',
    'sack_fumbles': 'Sack Fumbles',
    'sack_fumbles_lost': 'Sack Fumbles Lost',
    'passing_air_yards': 'Pass Air Yds',
    'passing_yards_after_catch': 'Pass YAC',
    'passing_first_downs': 'Pass 1D',
    'passing_epa': 'Pass EPA',
    'passing_cpoe': 'CPOE',
    'passing_2pt_conversions': 'Pass 2PT',
    'pacr': 'PACR',
    'carries': 'Rush Att',
    'rushing_yards': 'Rush Yds',
    'rushing_tds': 'Rush TDs',
    'rushing_fumbles': 'Rush Fumbles',
    'rushing_fumbles_lost': 'Rush Fumbles Lost',
    'rushing_first_downs': 'Rush 1D',
    'rushing_epa': 'Rush EPA',
    'rushing_2pt_conversions': 'Rush 2PT',
    'receptions': 'Rec',
    'targets': 'Tgt',
    'receiving_yards': 'Rec Yds',
    'receiving_tds': 'Rec TDs',
    'receiving_fumbles': 'Rec Fumbles',
    'receiving_fumbles_lost': 'Rec Fumbles Lost',
    'receiving_air_yards': 'Rec Air Yds',
    'receiving_yards_after_catch': 'Rec YAC',
    'receiving_first_downs': 'Rec 1D',
    'receiving_epa': 'Rec EPA',
    'receiving_2pt_conversions': 'Rec 2PT',
    'racr': 'RACR',
    'target_share': 'Target Share%',
    'air_yards_share': 'Air Yards Share%',
    'wopr': 'WOPR',
    'special_teams_tds': 'ST TDs',
    'def_tackles_solo': 'Def. Tackles (Solo)',
    'def_tackles_with_assist': 'Def. Tackles (w/ Ast)',
    'def_tackle_assists': 'Def. Tackle Ast',
    'def_tackles_for_loss': 'TFL',
    'def_tackles_for_loss_yards': 'TFL Yds',
    'def_fumbles_forced': 'FF (Forced)',
    'def_sacks': 'Sacks',
    'def_sack_yards': 'Sack Yds',
    'def_qb_hits': 'QB Hits',
    'def_interceptions': 'DEF INTs',
    'def_interception_yards': 'INT Yds',
    'def_pass_defended': 'PD (Passes Defended)',
    'def_tds': 'DEF TDs',
    'def_fumbles': 'DEF Fumbles',
    'def_safeties': 'Safeties',
    'misc_yards': 'Misc. Yds',
    'fumble_recovery_own': 'Fum Rec (Own)',
    'fumble_recovery_yards_own': 'Fum Rec Yds (Own)',
    'fumble_recovery_opp': 'Fum Rec (Opp)',
    'fumble_recovery_yards_opp': 'Fum Rec Yds (Opp)',
    'fumble_recovery_tds': 'Fum Rec TDs',
    'penalties': 'Penalties',
    'penalty_yards': 'Penalty Yds',
    'punt_returns': 'Punt Ret',
    'punt_return_yards': 'Punt Ret Yds',
    'kickoff_returns': 'KO Ret',
    'kickoff_return_yards': 'KO Ret Yds',
    'fg_made': 'FG Made',
    'fg_att': 'FG Att',
    'fg_missed': 'FG Missed',
    'fg_blocked': 'FG Blkd',
    'fg_long': 'Long FG',
    'fg_pct': 'FG%',
    'fg_made_0_19': 'FG Made 0–19',
    'fg_made_20_29': 'FG Made 20–29',
    'fg_made_30_39': 'FG Made 30–39',
    'fg_made_40_49': 'FG Made 40–49',
    'fg_made_50_59': 'FG Made 50–59',
    'fg_made_60_': 'FG Made 60+',
    'fg_missed_0_19': 'FG Missed 0–19',
    'fg_missed_20_29': 'FG Missed 20–29',
    'fg_missed_30_39': 'FG Missed 30–39',
    'fg_missed_40_49': 'FG Missed 40–49',
    'fg_missed_50_59': 'FG Missed 50–59',
    'fg_missed_60_': 'FG Missed 60+',
    'fg_made_list': 'FGs Made (List)',
    'fg_missed_list': 'FGs Missed (List)',
    'fg_blocked_list': 'FGs Blocked (List)',
    'fg_made_distance': 'Made FG Dist.',
    'fg_missed_distance': 'Missed FG Dist.',
    'fg_blocked_distance': 'Blocked FG Dist.',
    'pat_made': 'PAT Made',
    'pat_att': 'PAT Att',
    'pat_missed': 'PAT Missed',
    'pat_blocked': 'PAT Blkd',
    'pat_pct': 'PAT%',
    'gwfg_made': 'GW FG Made',
    'gwfg_att': 'GW FG Att',
    'gwfg_missed': 'GW FG Missed',
    'gwfg_blocked': 'GW FG Blkd',
    'gwfg_distance': 'GW FG Dist.',
    'fantasy_points': 'Fantasy Pts',
    'fantasy_points_ppr': 'Fantasy Pts (PPR)'
}